ARG BASE

FROM ${BASE}

ARG AUTHOR
ARG VERSION

LABEL maintainer=${AUTHOR} version=${VERSION}

ENV LOCAL_PATH /opt/shardingsphere-proxy

COPY shardingsphere-distribution/shardingsphere-proxy-distribution/target/apache-shardingsphere-${VERSION}-shardingsphere-proxy-bin/ ${LOCAL_PATH}/

ENTRYPOINT ${LOCAL_PATH}/bin/start.sh ${PORT} && tail -f ${LOCAL_PATH}/logs/stdout.log