ARG BASE

FROM ${BASE}

ARG AUTHOR
ARG VERSION

LABEL maintainer=${AUTHOR} version=${VERSION}

ENV LOCAL_PATH /opt/beagle-xc-dbproxy

COPY shardingsphere-distribution/shardingsphere-proxy-distribution/target/apache-shardingsphere-5.1.2-shardingsphere-proxy-bin/ ${LOCAL_PATH}/

ARG MYSQL_CONNECTOR_VERSION

COPY .tmp/mysql-connector-java-$MYSQL_CONNECTOR_VERSION.jar ${LOCAL_PATH}/ext-lib/mysql-connector-java-$MYSQL_CONNECTOR_VERSION.jar

ENTRYPOINT ${LOCAL_PATH}/bin/start.sh ${PORT} && tail -f ${LOCAL_PATH}/logs/stdout.log